tasks:
   - init: yarn install && yarn build && (cd scripts && pipenv install)
     command: npm start & node app.js
ports:
   - port: 3000
     onOpen: open-browser
   - port: 5000
     onOpen: ignore
